# Site settings
title: 狼来了
email: zhiqiangzhan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  詹子知，Full Stack Engineer，资深码农，精通系统底层和各种编程语言理论。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jameszhan.github.io" # the base hostname & protocol for your site
twitter_username: jameszhan
github_username:  jameszhan
permalink: /:year/:month/:day/:title

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
