# Site settings
# aginate: 2
# paginate_path: "page:num"
# host: 0.0.0.0
# port: 4000
# destination: ./_site
# plugins: ./_plugins
# layouts: ./_layouts
# timezone: 'Asia/Shanghai'
timezone: 'ETC/GMT'
title: 尽管扯淡
username: 詹子知
role: 'Full Stack Engineer'
email: zhiqiangzhan@gmail.com
description: "资深码农，程序设计语言控"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jameszhan.github.io" # the base hostname & protocol for your site
twitter_username: jameszhan
github_username:  jameszhan
weibo_username: zizhizhan
permalink: /:year/:month/:day/:title.html
exclude: [README.md, Gemfile, Gemfile.lock, LICENSE, spm_modules]

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]

collections:
    sitemap:
        output: true
        permalink: /:group/:name.html
    demos:
        output: true
        permalink: /demos/:path.html
    tpls:
        output: true
        permalink: /assets/tpls/:path.tpl

